---
title: "Final_Project"
author: "Alex Alon, Owen Bevis, Arielle Glass, Susan Gogolski"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      error = FALSE)
```

### Load libraries and data
```{r libraries}
library(tidyverse)
library(htmlwidgets)
library(leaflet)
library(leaflegend)
library(purrr)
library(viridis)
```

```{r data}
explosions <- read_csv("data/nuclear_explosions.csv")
```

```{r AL}
# Alex's graph


```

```{r OB}
# Owen's graph

# Github link: https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-08-20

avg <- function(x, y) {
  num <- (x + y) / 2
}

explosions2 <- explosions %>% 
  mutate(average = map2_dbl(.x = yield_lower, .y = yield_upper, 
                        ~ avg(.x, .y))) %>% 
  mutate(scaled_average = average / 1000) %>% 
  mutate(popup_info = paste0("[b] This is a test: [/b]", scaled_average))

explosions2

summarize(explosions2,
          mean = mean(average, na.rm = TRUE),
          min = min(average, na.rm = TRUE),
          max = max(average, na.rm = TRUE))

explosions2 %>% 
  ggplot() +
  geom_histogram(aes(x = average), binwidth = 1000)

explosions2 %>% 
  ggplot() +
  geom_histogram(aes(x = scaled_average))

summarize(explosions2,
          mean = mean(scaled_average, na.rm = TRUE),
          min = min(scaled_average, na.rm = TRUE),
          max = max(scaled_average, na.rm = TRUE))

pal <- colorNumeric(palette = 'viridis', 
                   domain = explosions2$scaled_average,
                   na.color = NA)


# To do:
# Add popups
# Add better title.

leaflet() %>% 
  addTiles() %>% 
  addProviderTiles("Thunderforest.Landscape") %>% 
  addCircleMarkers(data = explosions2, lat = ~ latitude, lng = ~ longitude,
                   radius = ~ scaled_average, 
                   popup = ~ popup_info,
                   stroke = FALSE, fillOpacity = 0.5,
                   color = ~ pal(scaled_average)) %>% 
  addLegend(data = explosions2,
            pal = pal,
            values = ~ scaled_average,
            title = "Worldwide nuclear explosions")


numPal <- colorFactor('viridis', explosions2$average)
leaflet(explosions2) %>%
  addTiles() %>%
  addSymbolsSize(values = ~ average,
                 lat = ~ latitude, 
                 lng = ~ longitude,
                 shape = 'circle',
                 color = ~ numPal(average),
                 fillColor = ~ numPal(average),
                 opacity = .5,
                 baseSize = 1)
```
  addLegendSize(
    values = ~ 10^(average),
    pal = numPal,
    title = 'Magnitude',
    baseSize = 1,
    shape = 'circle',
    orientation = 'horizontal',
    opacity = .5,
    fillOpacity = .3,
    position = 'bottomleft',
    breaks = 5)
  
  

```{r AG}
# Arielle's graph


```

```{r SG}
# Susan's graph


```

